apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxds
spec:
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginxds
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
  selector:
    matchLabels:
      app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: daemonservice
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
