apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  namespace: dev-ns
  labels:
    app: dev-pod
spec:
  containers:
    - name: node-container
      image: httpd
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: devpodsvc
  namespace: dev-ns
spec:
  type: ClusterIP
  selector:
    app: dev-pod
  ports:
    - port: 80
      targetPort: 80
