apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: node-app
spec:
  containers:
    - name: node-container
      image: httpd
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 1m
          memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nodeappsvc
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 80
