apiVersion: v1
kind: ReplicationController
metadata:
  name: replicontroller
spec:
  replicas: 2
  selector:
    app: replicontroller
  template:
    metadata:
      name: replicontroller
      labels:
        app: replicontroller
    spec:
      containers:
        - name: replicontroller
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  type: NodePort
  selector:
    app: replicontroller
  ports:
    - port: 80
      targetPort: 80
