apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetexample
  labels:
    app: replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - image: nginx
          name: httpdcontainer
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: replicasetservice
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32761
