apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapplication
spec:
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: dockerhandson/spring-boot-mongo:1
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB_HOSTNAME
              value: mongostate-svc
            - name: MONGO_DB_USERNAME
              value: dev
            - name: MONGO_DB_PASSWORD
              value: pass@123
---
apiVersion: v1
kind: Service
metadata:
  name: springstatesvc
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32665
