apiVersion: apps/v1
kind: Deployment
metadata:
  name: sptringapp
spec:
  selector:
    matchLabels:
      app: sptringapp
  template:
    metadata:
      labels:
        app: sptringapp
    spec:
      containers:
        - name: sptringapp
          image: dockerhandson/spring-boot-app:1
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB_HOSTNAME
              value: mongoservice
            - name: MONGO_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: mongo_db_username
                  name: mongoconfig
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo_password
                  name: mongosecret
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
spec:
  type: NodePort
  selector:
    app: sptringapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32565
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mongoconfig
# data:
#   mongo_db_username: "devdb"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongosecret
# type: Opaque
# data:
#   mongo_password: ZGV2ZGJAMTIzCg==
